# our R base image
FROM r-base

# install packages
# these are ones I like
RUN echo 'install.packages(c("ggplot2"), repos="http://cran.us.r-project.org", dependencies=TRUE)' > /tmp/packages.R \
    && Rscript /tmp/packages.R

RUN apt-get update && apt-get install -y \
	libcurl4-openssl-dev \
	libssl-dev \
	libcairo-dev

RUN echo 'install.packages("Rserve",,"http://rforge.net/",type="source")' > /tmp/packages2.R \
    && Rscript /tmp/packages2.R

# Disable development tools
RUN chmod o-rwx \
	/usr/lib/gcc /usr/lib/python* /usr/lib/tcltk /usr/lib/valgrind \
	/sbin /usr/sbin /usr/local/bin \
	/usr/bin/* /bin/* && \
    chmod o+x \
	/bin/bash /bin/ls /bin/uname /bin/sh && \
    chmod o+rx \
	/usr/bin/R /usr/bin

# create an R user
ENV HOME /home/ruser
RUN groupadd -g @GROUPID@ ruser && \
    useradd -u @USERID@ -g @GROUPID@ --create-home --home-dir $HOME ruser && \
    chown -R ruser:ruser $HOME

WORKDIR $HOME
USER ruser

# set the command
ADD Rserv.conf Rserv.conf
ADD Rserv.sh Rserv.sh

CMD /bin/bash Rserv.sh
